steps:
  # Install dependencies
  - name: 'node:20'
    id: 'install'
    entrypoint: 'npm'
    args: ['install', '--frozen-lockfile']
    dir: '.'

  # Run linting
  - name: 'node:20'
    id: 'lint'
    entrypoint: 'npm'
    args: ['run', 'lint']
    dir: '.'
    waitFor: ['install']

  # Run type checking
  - name: 'node:20'
    id: 'typecheck'
    entrypoint: 'npm'
    args: ['run', 'typecheck']
    dir: '.'
    waitFor: ['install']

  # Run unit tests
  - name: 'node:20'
    id: 'test-unit'
    entrypoint: 'npm'
    args: ['run', 'test:unit']
    dir: '.'
    waitFor: ['install']

  # Build the application
  - name: 'node:20'
    id: 'build'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: '.'
    waitFor: ['lint', 'typecheck', 'test-unit']

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/bibanna/bibanna-app:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/bibanna/bibanna-app:latest'
      - '--cache-from'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/bibanna/bibanna-app:latest'
      - '.'
    waitFor: ['build']

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/bibanna/bibanna-app'
    waitFor: ['docker-build']

  # Run database migrations against staging
  - name: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/bibanna/bibanna-app:${SHORT_SHA}'
    id: 'migrate-staging'
    entrypoint: 'npx'
    args: ['tsx', 'scripts/migrate.ts', 'up']
    env:
      - 'DATABASE_URL=${_STAGING_DATABASE_URL}'
    waitFor: ['docker-push']

  # Validate migrations
  - name: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/bibanna/bibanna-app:${SHORT_SHA}'
    id: 'validate-migrations'
    entrypoint: 'npx'
    args: ['tsx', 'scripts/migrate.ts', 'validate']
    env:
      - 'DATABASE_URL=${_STAGING_DATABASE_URL}'
    waitFor: ['migrate-staging']

  # Deploy to GKE (staging)
  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'deploy-staging'
    args:
      - 'run'
      - '--filename=k8s/overlays/staging'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/bibanna/bibanna-app:${SHORT_SHA}'
      - '--location=${_REGION}'
      - '--cluster=${_STAGING_CLUSTER}'
    waitFor: ['migrate-staging']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'

  # Run E2E tests against staging
  - name: 'node:20'
    id: 'test-e2e'
    entrypoint: 'npm'
    args: ['run', 'test:e2e']
    dir: '.'
    env:
      - 'BASE_URL=${_STAGING_URL}'
    waitFor: ['deploy-staging']

  # Run database migrations against production
  - name: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/bibanna/bibanna-app:${SHORT_SHA}'
    id: 'migrate-production'
    entrypoint: 'npx'
    args: ['tsx', 'scripts/migrate.ts', 'up']
    env:
      - 'DATABASE_URL=${_PROD_DATABASE_URL}'
    waitFor: ['test-e2e']

  # Deploy to GKE (production) - only on main branch
  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'deploy-production'
    args:
      - 'run'
      - '--filename=k8s/overlays/production'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/bibanna/bibanna-app:${SHORT_SHA}'
      - '--location=${_REGION}'
      - '--cluster=${_PROD_CLUSTER}'
    waitFor: ['migrate-production']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'

substitutions:
  _REGION: 'us-central1'
  _STAGING_CLUSTER: 'bibanna-staging-gke'
  _PROD_CLUSTER: 'bibanna-production-gke'
  _STAGING_URL: 'https://staging.bibanna.dev'
  _STAGING_DATABASE_URL: ''  # Set via Cloud Build trigger or Secret Manager
  _PROD_DATABASE_URL: ''     # Set via Cloud Build trigger or Secret Manager

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/bibanna/bibanna-app:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/bibanna/bibanna-app:latest'
